CREATE VIEW VW_CONSULTA_FORNC_MES AS
	SELECT TOC.COD_PESSOA, TP.RAZAO_SOCIAL FORNECEDOR, TO_CHAR(TOC.DAT_ORDEM_COMPRA, 'MONTH') MES,
		   TO_CHAR(TOC.DAT_ORDEM_COMPRA, 'W') SEMANA,
		   COUNT(TOC.COD_ORDEM_COMPRA) QTD_PEDIDO,
		   TO_CHAR(ROUND(SUN(TI.VLR_TOT_ITEM),2), 'FM999G999G999G9990D00'), VALOR_COMPRA_ANO_2020,
		   TO_CHAR(ROUND(AVG(TI.VLR_TOT_ITEM),2), 'FM999G999G999G9990D00'), MEDIA_COMPRA_ANO_2020
	FROM TAB_ORDEM_COMPRA TOC,
	     TAB_OC_ITEM TI,
		 TAB_PESSOA TP
	WHERE (TOC.DAT_ORDEM_COMPRA) BETWEEN '01/01/2020' AND '31/12/2020'
	  AND TP.COD_PESSOA = TOC.COD_PESSOA
	  AND TI.COD_ORDEM_COMPRA = TOC.COD_ORDEM_COMPRA
	GROUP BY TOC.COD_PESSOA, TP.RAZAO_SOCIAL, TO_CHAR(TOC.DAT_ORDEM_COMPRA, 'MONTH'), 
		  TO_CHAR(TOC.DAT_ORDEM_COMPRA, 'MM'), 
		  TO_CHAR(TOC.DAT_ORDEM_COMPRA, 'W')
	ORDER BY TO_CHAR(TOC.DAT_ORDEM_COMPRA, 'MM'), 
	      TO_CHAR(TOC.DAT_ORDEM_COMPRA, 'W');